import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCog,
  faTimes,
  faBell,
  faChevronUp,
  faChevronDown,
  faSignOutAlt,
  faCheck,
  faToggleOff,
  faToggleOn,
  faEnvelope,
  faPhone,
  faAlignLeft,
  faGripHorizontal,
  faComment,
  faHeart,
  faTag,
  faStar,
  faHandPointUp,
  faUsers,
  faMoneyBill,
  faCertificate,
  faThumbsUp,
  faBan,
  faCalendarTimes,
  faSpinner,
  faFistRaised,
  faHandHoldingHeart,
  faHandPointer,
  faSort,
  faSortUp,
  faSortDown,
  faDotCircle,
  faCopy
} from "@fortawesome/free-solid-svg-icons";
import { faFacebookSquare } from "@fortawesome/free-brands-svg-icons";

library.add(faCog);
library.add(faTimes);
library.add(faBell);
library.add(faChevronUp);
library.add(faChevronDown);
library.add(faSignOutAlt);
library.add(faCheck);
library.add(faToggleOff);
library.add(faToggleOn);
library.add(faEnvelope);
library.add(faPhone);
library.add(faAlignLeft);
library.add(faGripHorizontal);
library.add(faComment);
library.add(faHeart);
library.add(faTag);
library.add(faStar);
library.add(faHandPointUp);
library.add(faUsers);
library.add(faMoneyBill);
library.add(faCertificate);
library.add(faThumbsUp);
library.add(faBan);
library.add(faCalendarTimes);
library.add(faSpinner);
library.add(faFistRaised);
library.add(faHandHoldingHeart);
library.add(faHandPointer);
library.add(faSort);
library.add(faSortUp);
library.add(faSortDown);
library.add(faDotCircle);
library.add(faCopy);
library.add(faFacebookSquare);
