import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCog,
  faDownload,
  faTimes,
  faBell,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faSignOutAlt,
  faCheck,
  faToggleOff,
  faToggleOn,
  faEnvelope,
  faPhone,
  faAlignLeft,
  faGripHorizontal,
  faComment,
  faHeart,
  faTag,
  faStar,
  faHandPointUp,
  faUsers,
  faUserCircle,
  faMoneyBill,
  faCertificate,
  faThumbsUp,
  faBan,
  faCalendarTimes,
  faSpinner,
  faFistRaised,
  faHandHoldingHeart,
  faHandPointer,
  faSort,
  faSortUp,
  faSortDown,
  faDotCircle,
  faCopy,
  faArrowRight,
  faMapMarker,
  faMapMarked,
  faGlobe,
  faQuestion,
  faUndoAlt,
  faEdit,
  faEye,
  faSync,
  faMarker,
  faLink,
  faInfoCircle,
  faShieldAlt,
  faGlobeAmericas,
  faThLarge,
  faCode,
} from "@fortawesome/free-solid-svg-icons";
import {
  faFacebookSquare,
  faInstagram,
  faTwitter,
  faFacebookMessenger,
  faWhatsapp,
  faWordpress,
} from "@fortawesome/free-brands-svg-icons";

library.add(faCog);
library.add(faDownload);
library.add(faTimes);
library.add(faBell);
library.add(faChevronUp);
library.add(faChevronDown);
library.add(faChevronLeft);
library.add(faChevronRight);
library.add(faSignOutAlt);
library.add(faCheck);
library.add(faToggleOff);
library.add(faToggleOn);
library.add(faEnvelope);
library.add(faPhone);
library.add(faAlignLeft);
library.add(faGripHorizontal);
library.add(faComment);
library.add(faHeart);
library.add(faTag);
library.add(faStar);
library.add(faHandPointUp);
library.add(faUsers);
library.add(faUserCircle);
library.add(faMoneyBill);
library.add(faCertificate);
library.add(faThumbsUp);
library.add(faBan);
library.add(faCalendarTimes);
library.add(faSpinner);
library.add(faFistRaised);
library.add(faHandHoldingHeart);
library.add(faHandPointer);
library.add(faSort);
library.add(faSortUp);
library.add(faSortDown);
library.add(faDotCircle);
library.add(faCopy);
library.add(faArrowRight);
library.add(faMapMarker);
library.add(faMapMarked);
library.add(faGlobe);
library.add(faQuestion);
library.add(faUndoAlt);
library.add(faEdit);
library.add(faEye);
library.add(faSync);
library.add(faMarker);
library.add(faLink);
library.add(faInfoCircle);
library.add(faShieldAlt);
library.add(faGlobeAmericas);
library.add(faThLarge);
library.add(faCode);

library.add(faFacebookSquare);
library.add(faInstagram);
library.add(faTwitter);
library.add(faFacebookMessenger);
library.add(faWhatsapp);
library.add(faWordpress);
